version: '3'
services:
  neo-db:
    image: neo4j:4.4-community
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/Neo4j
    volumes:
      - data:/data
      - logs:/logs

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=neo4j://neo-db:7687
      - USER_NAME=neo4j
      - PASSWORD=Neo4j
    depends_on:
     - neo-db
volumes:
  data:
  logs: